image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir public
    - find . -maxdepth 1 -mindepth 1 ! -name public ! -name .git -exec cp -r {} public/ \;
  artifacts:
    paths:
      - public
  only:
    - master
